%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Class:   laszewski
% Author:  Gregor von Laszewski
% License: CC BY-NC-SA 3.0
%          (http://creativecommons.org/licenses/by-nc-sa/3.0/)
%
% This Class has Is a heavily modified version of the Legrand Orange
% Book file And integrates And modifies the structure.tex file
% Version 2.0 (9/2/15). The original Legrand authors are
% Mathias Legrand (legrand.mathias@gmail.com) with modifications by
% Vel (vel@latextemplates.com). The structure file 
% was downloaded from http://www.LaTeXTemplates.com
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{laszewski}
              [2018/01/01 Book Format For Cloud Handbook]

\RequirePackage[hyphens]{url}
\LoadClass[11pt,felqn]{book}

\usepackage{comment}